name: Unstable

on:
    # TBD when this workflow should run
    pull_request:
    workflow_dispatch:
    #schedule:
    #  - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-22.04
    #Next line is in comment for testing with forked repository
    #if: github.repository == 'redis/redis-snap'
    strategy: 
        matrix:
            target-arch: [amd64, arm64]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        repository: redis/redis
        path: redis
    - name: Prepare for cross-compilation
      run: |
          sudo dpkg --add-architecture arm64
          sudo sed -i 's/^deb /deb [arch=amd64] /g' /etc/apt/sources.list
          cat <<_END_ | sudo tee /etc/apt/sources.list.d/crosscompile.list
          deb [arch=arm64] http://ports.ubuntu.com $(lsb_release -cs) main universe
          deb [arch=arm64] http://ports.ubuntu.com $(lsb_release -cs)-updates main universe
          _END_
    - name: Setup Snapcraft
      run: |
        sudo snap install snapcraft --classic
    - name: Build Snap
      env:
        SNAPCRAFT_BUILD_ENVIRONMENT: host
        SNAPCRAFT_BUILD_INFO: 1
      run: |
          echo "the architecture is ${{ matrix.target-arch }}"
          sudo snapcraft --verbose --target-arch ${{ matrix.target-arch }} --destructive-mode --enable-experimental-target-arch
#      continue-on-error: true #Consider removing this line after finishing testing
          
    -   name: Archive Snapcraft logs on failure
        # Can be removed when pushing to the real repository
        if: failure() # This step runs only if a previous step fails
        run: |
            LOG_DIR="${HOME}/.local/state/snapcraft"
            echo "Searching for logs in $LOG_DIR..."
            ls -R $LOG_DIR || echo "No logs found."
        continue-on-error: true # Ensure this step does not block execution

    -   name: Upload Snapcraft logs as artifact
        # Can be removed when pushing to the real repository
        if: failure() # Runs only on failure
        uses: actions/upload-artifact@v4
        with:
            name: snapcraft-logs
            path: ~/.local/state/snapcraft/log 
            
    - name: Upload
      run: |
          echo "placeholder for snap package upload"
          # for f in *.snap; do snapcraft upload --release=edge $f; done
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{secrets.SNAP_TOKEN}}
    - name: upload to artifacts
      # Can be removed when pushing to the real repository
      uses: actions/upload-artifact@v4
      with:
        name: redis-snap-${{ matrix.target-arch }}
        path: |
            *.snap

  test:
      needs: build
#      runs-on: ubuntu-22.04
      runs-on: ${{ matrix.arch == 'arm64' && 'ubuntu24-arm64-4-16' || 'ubuntu-latest' }}
      strategy:
          matrix:
              target-arch: [ amd64, arm64 ]
      steps:
          -   name: Download artifact
              uses: actions/download-artifact@v4
              with:
                  name: redis-snap-${{ matrix.target-arch }}
                  path: ./snap-artifacts
          -   name: Install the snap package
              run: |
                  SNAP_FILE=$(ls snap-artifacts/*.snap)
                  echo "Installing snap: $SNAP_FILE"
                  sudo snap install --dangerous $SNAP_FILE
          -   name: Verify snap installation
              run: |
                  snap list | grep redis
                  snap services | grep redis || echo "Redis service not found."